services:
  aton_postgres_db:
    image: postgres:15-alpine
    container_name: aton_test_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aton_web
    restart: always
    depends_on:
      aton_postgres_db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/app/wwwroot
    command: >
      sh -c "sleep 10 && dotnet AtonTest.dll"

volumes:
  postgres_data:
  static_volume: